import { useState } from 'react';
import PeerCard from '../components/PeerCard';

const MOCK_PULSE = "Something heavy moved through this week — a particular kind of tired that isn't fixed by sleep, the weight of sending another application into silence. Several people named the loneliness of it, the way the days blur without structure. A few found small moments of something steadier. Whatever you carried into this week, you weren't carrying it alone.";

const MOCK_PEERS = [
  { id: '1', mood: 'Navigating rejection fatigue after months of applications', duration: '4 months', looking_for: 'Emotional Support', field: 'Tech' },
  { id: '2', mood: 'Pre-interview anxiety that won\'t quiet down', duration: '2 months', looking_for: 'Interview Practice', field: 'Finance' },
  { id: '3', mood: 'Career transition uncertainty after 12 years in one field', duration: '6 months', looking_for: 'Job Buddy', field: 'Healthcare' },
  { id: '4', mood: 'Feeling isolated — can\'t talk about this with people I know', duration: '3 months', looking_for: 'Emotional Support', field: 'Education' },
  { id: '5', mood: 'OPT timeline pressure making every rejection feel enormous', duration: '5 months', looking_for: 'Networking', field: 'Data Science' },
  { id: '6', mood: 'Rebuilding identity after a senior-level layoff', duration: '2 months', looking_for: 'Emotional Support', field: 'Product Management' },
];

const FILTERS = ['All', 'Emotional Support', 'Job Buddy', 'Interview Practice', 'Networking'];

const STATS = [
  { value: '247', label: 'Active this week' },
  { value: '38%', label: 'On visa timelines' },
  { value: '34%', label: 'Mid-career transitions' },
];

export default function Community({ userId }) {
  const [filter, setFilter] = useState('All');

  const peers = filter === 'All' ? MOCK_PEERS : MOCK_PEERS.filter(p => p.looking_for === filter);

  return (
    <div className="screen">
      <h1 className="page-title">Find your <em>people</em></h1>
      <p className="page-sub">Anonymous peer support — no real names, no judgment.</p>

      {/* Community Pulse */}
      <div className="section-label">This Week's Pulse · Generated by Claude</div>
      <div className="card" style={{ marginBottom: 20, borderLeft: '3px solid var(--sage)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 12 }}>
          <div style={{ width: 7, height: 7, borderRadius: '50%', background: 'var(--sage)', animation: 'lpulse 2s infinite' }} />
          <span style={{ fontSize: 11, fontFamily: "'DM Mono', monospace", color: 'var(--sage)', letterSpacing: '0.06em' }}>LIVE</span>
        </div>
        <p style={{ fontSize: 14, color: 'var(--text2)', lineHeight: 1.75, fontStyle: 'italic', fontWeight: 300 }}>
          {MOCK_PULSE}
        </p>
        <div style={{ display: 'flex', gap: 8, marginTop: 16 }}>
          {STATS.map(s => (
            <div key={s.label} style={{
              flex: 1, background: 'var(--sage-light)',
              borderRadius: 10, padding: '10px 8px', textAlign: 'center',
            }}>
              <div style={{ fontSize: 18, fontWeight: 500, color: 'var(--sage)', fontFamily: "'Fraunces', serif" }}>{s.value}</div>
              <div style={{ fontSize: 10, color: 'var(--text3)', marginTop: 2, fontWeight: 300, lineHeight: 1.3 }}>{s.label}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Filter tabs */}
      <div className="section-label">Connect with someone</div>
      <div style={{ display: 'flex', gap: 6, overflowX: 'auto', marginBottom: 16, paddingBottom: 4 }}>
        {FILTERS.map(f => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            style={{
              padding: '7px 14px', borderRadius: 20, flexShrink: 0,
              background: filter === f ? 'var(--sage)' : 'transparent',
              border: `1px solid ${filter === f ? 'var(--sage)' : 'var(--border2)'}`,
              color: filter === f ? 'white' : 'var(--text2)',
              fontSize: 12, fontWeight: 500, cursor: 'pointer',
              fontFamily: 'inherit', transition: 'all 0.2s',
            }}
          >
            {f}
          </button>
        ))}
      </div>

      {peers.map(peer => <PeerCard key={peer.id} peer={peer} userId={userId} />)}

      <p style={{ fontSize: 11, color: 'var(--text3)', textAlign: 'center', marginTop: 16, fontWeight: 300, lineHeight: 1.6 }}>
        All profiles are anonymous. No real names, no identifying details.
      </p>

      <style>{`
        @keyframes lpulse { 0%,100% { opacity:1; } 50% { opacity:0.3; } }
      `}</style>
    </div>
  );
}
